# Autogenerated wrapper script for Qt6Positioning_jll for aarch64-linux-gnu-cxx11
export libqt6positioning, libqt6positioningquick

using Qt6Base_jll
using Qt6Declarative_jll
JLLWrappers.@generate_wrapper_header("Qt6Positioning")
JLLWrappers.@declare_library_product(libqt6positioning, "libQt6Positioning.so.6")
JLLWrappers.@declare_library_product(libqt6positioningquick, "libQt6PositioningQuick.so.6")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6Declarative_jll)
    JLLWrappers.@init_library_product(
        libqt6positioning,
        "lib/libQt6Positioning.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6positioningquick,
        "lib/libQt6PositioningQuick.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
