# Autogenerated wrapper script for Qt6Positioning_jll for x86_64-apple-darwin
export libqt6positioning, libqt6positioningquick

using Qt6Base_jll
using Qt6Declarative_jll
JLLWrappers.@generate_wrapper_header("Qt6Positioning")
JLLWrappers.@declare_library_product(libqt6positioning, "@rpath/QtPositioning")
JLLWrappers.@declare_library_product(libqt6positioningquick, "@rpath/QtPositioningQuick")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6Declarative_jll)
    JLLWrappers.@init_library_product(
        libqt6positioning,
        "lib/QtPositioning.framework/Versions/A/QtPositioning",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6positioningquick,
        "lib/QtPositioningQuick.framework/Versions/A/QtPositioningQuick",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
